.catalog:
    name: Kubernetes
    version: v1.2.alpha4-rancher-1
    description: Manage a cluster of Linux containers as a single system to accelerate Dev and simplify Ops.
    uuid: kubernetes-1
    questions:
        - variable: "etcd"
          description: "Link to etcd service or stack/service"
          label: "etcd"
          type: "service"
          required: true

api-server:
    service_schemas:
        kubernetesReplicationController:
            resource_fields:
                template:
                    type: json
                    create: true
                    read: true
                    update: true
        kubernetesService:
            resource_fields:
                template:
                    type: json
                    create: true
                    read: true
                    update: true
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 8080
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

rancher-kubernetes-agent:
    health_check:
        request_line: GET /healthcheck HTTP/1.0
        port: 10240
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

scheduler:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10251
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2

controller-manager:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 10252
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
